@echo off

echo Starting VetCare Application...
echo Please wait while the application starts...

echo Compiling Java files...
javac -cp .;target/classes src/main/java/org/example/*.java src/main/java/org/example/dao/*.java src/main/java/org/example/entites/*.java src/main/java/org/example/interfacee/*.java

echo Running the application...
java -cp .;target/classes org.example.Main

echo Application has finished running.
pause
